var annotated_dup =
[
    [ "Ui", null, [
      [ "AutoYamsClass", "class_ui_1_1_auto_yams_class.html", null ],
      [ "VideoCapture", "class_ui_1_1_video_capture.html", null ]
    ] ],
    [ "AbstractException", "class_abstract_exception.html", "class_abstract_exception" ],
    [ "AdvancedPage", "class_advanced_page.html", "class_advanced_page" ],
    [ "AutoYams", "class_auto_yams.html", "class_auto_yams" ],
    [ "ConfigFile", "class_config_file.html", "class_config_file" ],
    [ "ConfigManager", "class_config_manager.html", "class_config_manager" ],
    [ "ConfigPage", "class_config_page.html", "class_config_page" ],
    [ "Dice", "class_dice.html", "class_dice" ],
    [ "DiceDetector", "class_dice_detector.html", "class_dice_detector" ],
    [ "EventRedirector", "class_event_redirector.html", "class_event_redirector" ],
    [ "EventThrowDice", "class_event_throw_dice.html", "class_event_throw_dice" ],
    [ "FileDebug", "class_file_debug.html", "class_file_debug" ],
    [ "Game", "class_game.html", "class_game" ],
    [ "GamePage", "class_game_page.html", "class_game_page" ],
    [ "ImageOpenCV", "class_image_open_c_v.html", "class_image_open_c_v" ],
    [ "MenuPage", "class_menu_page.html", "class_menu_page" ],
    [ "Page", "class_page.html", "class_page" ],
    [ "PlayableMove", "class_playable_move.html", "class_playable_move" ],
    [ "Player", "class_player.html", "class_player" ],
    [ "qt_meta_stringdata_AdvancedPage_t", "structqt__meta__stringdata___advanced_page__t.html", "structqt__meta__stringdata___advanced_page__t" ],
    [ "qt_meta_stringdata_AutoYams_t", "structqt__meta__stringdata___auto_yams__t.html", "structqt__meta__stringdata___auto_yams__t" ],
    [ "qt_meta_stringdata_ConfigManager_t", "structqt__meta__stringdata___config_manager__t.html", "structqt__meta__stringdata___config_manager__t" ],
    [ "qt_meta_stringdata_ConfigPage_t", "structqt__meta__stringdata___config_page__t.html", "structqt__meta__stringdata___config_page__t" ],
    [ "qt_meta_stringdata_DiceDetector_t", "structqt__meta__stringdata___dice_detector__t.html", "structqt__meta__stringdata___dice_detector__t" ],
    [ "qt_meta_stringdata_EventRedirector_t", "structqt__meta__stringdata___event_redirector__t.html", "structqt__meta__stringdata___event_redirector__t" ],
    [ "qt_meta_stringdata_EventThrowDice_t", "structqt__meta__stringdata___event_throw_dice__t.html", "structqt__meta__stringdata___event_throw_dice__t" ],
    [ "qt_meta_stringdata_Game_t", "structqt__meta__stringdata___game__t.html", "structqt__meta__stringdata___game__t" ],
    [ "qt_meta_stringdata_GamePage_t", "structqt__meta__stringdata___game_page__t.html", "structqt__meta__stringdata___game_page__t" ],
    [ "qt_meta_stringdata_ImageOpenCV_t", "structqt__meta__stringdata___image_open_c_v__t.html", "structqt__meta__stringdata___image_open_c_v__t" ],
    [ "qt_meta_stringdata_MenuPage_t", "structqt__meta__stringdata___menu_page__t.html", "structqt__meta__stringdata___menu_page__t" ],
    [ "qt_meta_stringdata_Page_t", "structqt__meta__stringdata___page__t.html", "structqt__meta__stringdata___page__t" ],
    [ "qt_meta_stringdata_VideoCaptureWindow_t", "structqt__meta__stringdata___video_capture_window__t.html", "structqt__meta__stringdata___video_capture_window__t" ],
    [ "qt_meta_stringdata_VideoOpenCV_t", "structqt__meta__stringdata___video_open_c_v__t.html", "structqt__meta__stringdata___video_open_c_v__t" ],
    [ "qt_meta_stringdata_VideoPage_t", "structqt__meta__stringdata___video_page__t.html", "structqt__meta__stringdata___video_page__t" ],
    [ "Score", "class_score.html", "class_score" ],
    [ "Scoring", "class_scoring.html", "class_scoring" ],
    [ "Ui_AutoYamsClass", "class_ui___auto_yams_class.html", "class_ui___auto_yams_class" ],
    [ "Ui_VideoCapture", "class_ui___video_capture.html", "class_ui___video_capture" ],
    [ "VideoCaptureDevice", "class_video_capture_device.html", "class_video_capture_device" ],
    [ "VideoCaptureWindow", "class_video_capture_window.html", "class_video_capture_window" ],
    [ "VideoOpenCV", "class_video_open_c_v.html", "class_video_open_c_v" ],
    [ "VideoPage", "class_video_page.html", "class_video_page" ]
];